version: '2'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db   #depends on database 

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
       - POSTGRES_HOST_AUTH_METHOD=trust # Authication for enabled

volumes:
  postgres_data:
